count_self_blocks: true
delay_day: 0
dis_weight:
- 1
- 1
fall_ill:
- 0.2
- 0.1
new_matrix: false
num_days: 90
prior_res:
- 0
- 0
rec_weights:
- 2
- 2
scale: 1000
trans_prob:
- 0.04
- 0.01
n_clusters: 100
scaled_p_ER: 0.5
m_BA: 30
large_resp:
- 1.0
- 1.0